spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: sxn700320
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true #是否答应SQL语句
    hibernate:
      ddl-auto: update #无则创建表，有则不变
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect